name: Build Aria2c

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: moha-master/aria2
        ref: master
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool \
          pkg-config libcppunit-dev libssl-dev zlib1g-dev \
          gettext autopoint
    
    - name: Configure and build Linux
      run: |
        autoreconf -i
        ./configure --prefix=/usr/local
        make -j$(nproc)
    
    - name: Strip and package Linux binary
      run: |
        mkdir -p artifacts/linux
        cp src/aria2c artifacts/linux/
        strip artifacts/linux/aria2c
    
    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: aria2-linux
        path: artifacts/linux/aria2c

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: moha-master/aria2
        ref: master
    
    - name: Set up cross-compilation environment
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          make binutils autoconf automake autotools-dev libtool \
          patch ca-certificates \
          pkg-config git curl dpkg-dev gcc-mingw-w64 g++-mingw-w64 \
          autopoint libcppunit-dev libxml2-dev libgcrypt20-dev lzip \
          python3-docutils
        
        export HOST=x86_64-w64-mingw32
        export PREFIX=/usr/local/$HOST
        
        mkdir -p deps && cd deps
        curl -L -O https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz
        curl -L -O https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-2.5.0.tar.bz2
        curl -L -O https://www.sqlite.org/2023/sqlite-autoconf-3430100.tar.gz
        curl -L -O https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz
        curl -L -O https://github.com/c-ares/c-ares/releases/download/cares-1_19_1/c-ares-1.19.1.tar.gz
        curl -L -O https://libssh2.org/download/libssh2-1.11.0.tar.bz2
        
        tar xf gmp-6.3.0.tar.xz && cd gmp-6.3.0
        ./configure --disable-shared --enable-static --prefix=$PREFIX \
          --host=$HOST --disable-cxx --enable-fat \
          CFLAGS="-mtune=generic -O2 -g0"
        make -j$(nproc) install && cd ..
        
        tar xf expat-2.5.0.tar.bz2 && cd expat-2.5.0
        ./configure --disable-shared --enable-static --prefix=$PREFIX \
          --host=$HOST --build=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE)
        make -j$(nproc) install && cd ..
        
        tar xf sqlite-autoconf-3430100.tar.gz && cd sqlite-autoconf-3430100
        ./configure --disable-shared --enable-static --prefix=$PREFIX \
          --host=$HOST --build=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE)
        make -j$(nproc) install && cd ..
        
        tar xf zlib-1.3.1.tar.gz && cd zlib-1.3.1
        CC=$HOST-gcc AR=$HOST-ar LD=$HOST-ld RANLIB=$HOST-ranlib \
        STRIP=$HOST-strip ./configure --prefix=$PREFIX --static
        make -j$(nproc) install && cd ..
        
        tar xf c-ares-1.19.1.tar.gz && cd c-ares-1.19.1
        ./configure --disable-shared --enable-static --without-random \
          --prefix=$PREFIX --host=$HOST \
          --build=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE) LIBS="-lws2_32"
        make -j$(nproc) install && cd ..
        
        tar xf libssh2-1.11.0.tar.bz2 && cd libssh2-1.11.0
        ./configure --disable-shared --enable-static --prefix=$PREFIX \
          --host=$HOST --build=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE) \
          LIBS="-lws2_32"
        make -j$(nproc) install && cd ../..
    
    - name: Build aria2 for Windows
      run: |
        export HOST=x86_64-w64-mingw32
        export PREFIX=/usr/local/$HOST
        
        autoreconf -i
        ./mingw-config
        make -j$(nproc)
        $HOST-strip src/aria2c.exe
        
        mkdir -p artifacts/windows
        cp src/aria2c.exe artifacts/windows/
    
    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: aria2-windows
        path: artifacts/windows/aria2c.exe
