name: Build Aria2c

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: moha-master/aria2
        ref: master

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool \
          pkg-config libcppunit-dev libssl-dev zlib1g-dev \
          gettext autopoint

    - name: Configure and build Linux
      run: |
        autoreconf -i
        ./configure --prefix=/usr/local
        make -j$(nproc)

    - name: Strip and package Linux binary
      run: |
        mkdir -p artifacts/linux
        cp src/aria2c artifacts/linux/
        strip artifacts/linux/aria2c

    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: aria2-linux
        path: artifacts/linux/aria2c

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: moha-master/aria2
        ref: master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t aria2-mingw -f Dockerfile.mingw .

    - name: Prepare custom build directory
      run: mkdir -p aria2_custom

    - name: Run Docker container and compile
      run: |
        docker run --name aria2-build -v $(pwd)/aria2_custom:/aria2_custom aria2-mingw /bin/bash -c "
          cp -r /aria2/* /aria2_custom/

          cd /aria2_custom

          autoreconf -i
          ./mingw-config
          make -j$(nproc)

          i686-w64-mingw32-strip src/aria2c.exe
        "

    - name: Extract compiled binary
      run: |
        ls -lh aria2_custom/src/aria2c.exe

        mkdir -p artifacts/windows
        cp aria2_custom/src/aria2c.exe artifacts/windows/

        file artifacts/windows/aria2c.exe

    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: aria2-windows
        path: artifacts/windows/aria2c.exe
